# Generated by Django 6.1.1 on 2026-09-05 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True, verbose_name='Код')),
                ('label_ru', models.CharField(max_length=100, verbose_name='Название')),
                ('color_hex', models.CharField(default='#546670', max_length=7, verbose_name='Цвет на карте')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('telegram_username', models.CharField(blank=True, max_length=100, verbose_name='Username')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Заблокирован')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'автор заявки',
                'verbose_name_plural': 'авторы заявок',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'На модерации'), ('published', 'Опубликовано'), ('resolved', 'Устранено'), ('rejected', 'Отклонено')], db_index=True, default='pending', max_length=20, verbose_name='Статус')),
                ('lat', models.FloatField(verbose_name='Широта')),
                ('lng', models.FloatField(verbose_name='Долгота')),
                ('description', models.TextField(blank=True, verbose_name='Описание от автора')),
                ('address_hint', models.TextField(blank=True, verbose_name='Адрес')),
                ('photo_storage', models.CharField(default='onedrive', max_length=20, verbose_name='Хранилище')),
                ('photo_ref', models.TextField(verbose_name='Ссылка на фото в хранилище')),
                ('resolved_photo_ref', models.TextField(blank=True, verbose_name='Фото после устранения')),
                ('moderation_notes', models.TextField(blank=True, verbose_name='Заметки модератора')),
                ('rejected_reason', models.TextField(blank=True, verbose_name='Причина отклонения')),
                ('telegram_message_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Прислано')),
                ('moderated_at', models.DateTimeField(blank=True, null=True, verbose_name='Промодерировано')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Устранено')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='reports.category', verbose_name='Категория')),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_reports', to=settings.AUTH_USER_MODEL, verbose_name='Модератор')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='reports.reporter', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'заявка',
                'verbose_name_plural': 'заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=20, verbose_name='Было')),
                ('new_status', models.CharField(max_length=20, verbose_name='Стало')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='reports.report', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'запись истории',
                'verbose_name_plural': 'история статусов',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', 'category'], name='reports_rep_status_54a05f_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['lat', 'lng'], name='reports_rep_lat_1f73a2_idx'),
        ),
    ]
