# Generated by Django 6.1.1 on 2026-09-05 18:02

import reports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_seed_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='photo_storage',
            field=models.CharField(default=reports.models.default_photo_storage, max_length=20, verbose_name='Хранилище'),
        ),
    ]
