# Generated by Django 6.1.1 on 2026-09-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_report_photo_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='label_uz',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название (узб)'),
        ),
        migrations.AddField(
            model_name='reporter',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('uz', 'O‘zbekcha')], default='ru', max_length=5, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='category',
            name='label_ru',
            field=models.CharField(max_length=100, verbose_name='Название (рус)'),
        ),
    ]
