# Generated by Django 6.1.1 on 2026-09-05 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_seed_uz_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporter',
            name='language_chosen',
            field=models.BooleanField(default=False, verbose_name='Язык выбран'),
        ),
    ]
