"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "dev-insecure-change-me")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "1") == "1"

ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'reports',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.template.context_processors.i18n',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("DB_NAME", "pandus"),
        "USER": os.environ.get("DB_USER", "pandus"),
        "PASSWORD": os.environ.get("DB_PASSWORD", ""),
        "HOST": os.environ.get("DB_HOST", "localhost"),
        "PORT": os.environ.get("DB_PORT", "5432"),
    }
}

# На старте, пока Postgres не поднят, можно работать на SQLite:
#   USE_SQLITE=1 python manage.py runserver
if os.environ.get("USE_SQLITE") == "1":
    DATABASES["default"] = {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "ru"

LANGUAGES = [
    ("ru", "Русский"),
    ("uz", "O‘zbekcha"),
]
LOCALE_PATHS = [BASE_DIR / "locale"]
USE_I18N = True

TIME_ZONE = "Asia/Tashkent"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"},
}


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

# --- Хранилище фото (OneDrive через Microsoft Graph) ---
ONEDRIVE_CLIENT_ID = os.environ.get("ONEDRIVE_CLIENT_ID", "")
ONEDRIVE_CLIENT_SECRET = os.environ.get("ONEDRIVE_CLIENT_SECRET", "")
ONEDRIVE_TENANT_ID = os.environ.get("ONEDRIVE_TENANT_ID", "consumers")
ONEDRIVE_FOLDER = os.environ.get("ONEDRIVE_FOLDER", "pandus")

# --- Telegram ---
TELEGRAM_BOT_TOKEN = os.environ.get("TELEGRAM_BOT_TOKEN", "")

# --- Хранилище фотографий ---
# local | onedrive
PHOTO_STORAGE = os.environ.get("PHOTO_STORAGE", "local")
PHOTO_LOCAL_ROOT = Path(os.environ.get("PHOTO_LOCAL_ROOT", BASE_DIR / "photos"))  # вне static/, наружу не раздаётся

# ============================================================
# Безопасность боевого режима
# ============================================================
# Включается автоматически при DEBUG=False, чтобы нельзя было
# случайно выкатить сайт с настройками разработки.

if not DEBUG:
    # Ключ подписывает сессии и токены сброса пароля. Со значением по
    # умолчанию сессию модератора можно подделать, поэтому лучше упасть
    # при старте, чем молча работать уязвимым.
    if SECRET_KEY in ("", "dev-insecure-change-me") or SECRET_KEY.startswith("django-insecure-"):
        raise ImproperlyConfigured(
            "DJANGO_SECRET_KEY не задан. Сгенерируйте ключ командой:\n"
            "  python -c \"import secrets; print(secrets.token_urlsafe(64))\"\n"
            "и добавьте его в .env"
        )

    if "*" in ALLOWED_HOSTS:
        raise ImproperlyConfigured("ALLOWED_HOSTS не должен содержать '*' в боевом режиме")

    # HTTPS
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000          # год
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    # Nginx/Caddy терминируют TLS и передают исходную схему этим заголовком
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

    # Прочее
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SESSION_COOKIE_HTTPONLY = True
    X_FRAME_OPTIONS = "DENY"
    CSRF_TRUSTED_ORIGINS = [
        f"https://{h.strip()}" for h in ALLOWED_HOSTS if h.strip() and h != "localhost"
    ]

    # Сессия модератора живёт сутки и закрывается вместе с браузером
    SESSION_COOKIE_AGE = 60 * 60 * 24
    SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# --- Лимиты приёма заявок (защита от заваливания карты мусором) ---
REPORTS_PER_HOUR = int(os.environ.get("REPORTS_PER_HOUR", "5"))
REPORTS_PER_DAY = int(os.environ.get("REPORTS_PER_DAY", "20"))

# --- Почта ---
# Нужна только для восстановления пароля модератора. Если SMTP не настроен,
# пароль меняется командой: python manage.py changepassword <логин>
if not DEBUG:
    DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "noreply@localhost")
    _email_host = os.environ.get("EMAIL_HOST", "")
    if _email_host:
        MAILERS = {
            "default": {
                "BACKEND": "django.core.mail.backends.smtp.EmailBackend",
                "OPTIONS": {
                    "host": _email_host,
                    "port": int(os.environ.get("EMAIL_PORT", "587")),
                    "username": os.environ.get("EMAIL_HOST_USER", ""),
                    "password": os.environ.get("EMAIL_HOST_PASSWORD", ""),
                    "use_tls": True,
                },
            }
        }
    else:
        MAILERS = {"default": {"BACKEND": "django.core.mail.backends.dummy.EmailBackend"}}
